### ISSUE TITLE
Action failing

### ISSUE THREAD

**Issue by elio-developer** [Apple-Actions/download-provisioning-profiles#20]
Hi,

I implemented Apple-Actions/import-codesign-certs@v1 to get the certificates but when running Apple-Actions/download-provisioning-profiles@v1 im getting the following error: Error: error:0909006C:PEM routines:get_name:no start line

I event forked your Example project, put in my keys and it gives me the same error.

**Comment by scriptBoris** [comment]
error:1E08010C:DECODER routines::unsupported
I get it error on Apple-Actions/download-provisioning-profiles@v3

**Comment by anasrehmankhanllc** [comment]
@elio-developer @scriptBoris Hi do you guys able to solve it? i am getting the same issue

```
      - name: Download Provisioning Profiles
        id: provisioning
        uses: apple-actions/download-provisioning-profiles@v1
        with: 
          bundle-id: com.mydmain.com
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
```
          
   
          
```
          Error: error:1E08010C:DECODER routines::unsupported
```
